#!/bin/sh

dialog --title "Gettting Current Date and Time based on Time zone" --inputbox "Insert Continent(Space)City" 100 100 2> /tmp/tmp1


out=`cat /tmp/tmp1`
name=($out)

export TZ="${name[0]}"/"${name[1]}"

dialog --title "" --infobox "Current date and time is:\n`date`" 100 100
