#!/bin/sh

dialog --title "Gettting Current Date and Time based on Time zone" --inputbox "Insert Continent(Space)City" 50 50 4> /tmp/t1


out=`cat /tmp/t1`
array_name=($out)
export TZ="${array_name[0]}"/"${array_name[1]}"

dialog --title "" --infobox "Current date and time is:\n`date`" 50 50
