#!/bin/sh

DIALOG=${DIALOG=dialog}

$DIALOG --title "Timezone" --clear \
        --inputbox "Please put your desired Continent/Country Name: " 50 50 2>/tmp/input.$$
        
        ab=$(export TZ=`cat /tmp/input.$$`;date)
        
        MSG="Time is: $ab \n\nContinue?"
        
        $DIALOG --yesno "$MSG" 15 20
        
        
